# Generated by Django 5.2.6 on 2025-09-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_specification_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
